forestfires <- data.frame(read.csv("forestfires.csv",header = T))
opar <- par(no.readonly = TRUE)
par(mfrow=c(2,2))
plot(forestfires$area,forestfires$temp, main="Scatterplot of area vs temp")
plot(forestfires$area,forestfires$month, main="Scatterplot of area vs month")
plot(forestfires$area,forestfires$DC, main="Scatterplot of area vs DC")
plot(forestfires$area,forestfires$RH, main="Scatterplot of area vs RH")
par(opar)
hist(forestfires$wind, main = "Histogram of wind speed")
lines(density(forestfires$wind), col="blue",lwd=2)
mean(forestfires$wind)
quantile(forestfires$wind)
hist(forestfires$wind,freq=FALSE,breaks=12, main ="Histogram of wind speed, density curve")
lines(density(forestfires$wind), col="blue",lwd=2) 
library(ggplot2)
qplot(forestfires$month,data=forestfires, color = forestfires$month,geom="density")
pairs(~temp+RH+DC+DMC, data=forestfires,main="Basic scatter plot matrix")
cor(forestfires[c("temp","RH","DC","DMC")])#The highest numerical value whether positive or negative shows higher correlation
boxplot(forestfires$wind, main="Box plot",ylab="wind")
boxplot(forestfires$ISI, main="Box plot",ylab="ISI")
boxplot(forestfires$DC, main="Box plot",ylab="DC")
hist(forestfires$DMC, main="histogram of DMC")
hist(log(forestfires$DMC),main="histogram of log DMC")
twitter<- data.frame(read.csv("M01_quasi_twitter.csv",header = T))
quantile(twitter$friends_count)
library(scatterplot3d)
scatterplot3d(twitter$created_at_year,twitter$education,twitter$age,highlight.3d=TRUE,main="3D Scatter Plot")
par(mfrow=c(1,2))
slices <- c(650,1000,900,300,14900)
lbls <- c("UK","Canada","India","Australia","US")
pct <- round(slices/sum(slices)*100)
lbls2 <- paste(lbls,"",pct,"%",sep="")
pie(slices,labels=lbls2,col=rainbow(length(lbls2)),main="pie chart with percentages")
library(plotrix)
pie3D(slices,labels=lbls,explode=0.1,main="3d pie chart")
par(mfrow=c(1,1))
d <- density(twitter$created_at_year)
plot(d,main="kernel density of created at year")
#3a
rawdata <- data.frame(read.csv("raw_data.csv",header = T))
normalize <- function(x){return((x-min(x))/max(x)-min(x))}
Ndata <- as.data.frame(lapply(rawdata,normalize))
#3b
boxplot(rawdata$A,main="Box plot of A")
boxplot(rawdata$B,main="Box plot of B")
boxplot(rawdata$C,main="Box plot of C")
boxplot(rawdata$D,main="Box plot of D")
#3c
boxplot(Ndata$A,main="Normalized data Boxplot of A")
boxplot(Ndata$B,main="Normalized data Boxplot of B")
boxplot(Ndata$C,main="Normalized data Boxplot of C")
boxplot(Ndata$D,main="Normalized data Boxplot of D")
#3d
#By normalization we rescaled the boxplots into same range which is easier to compare the data. The normalized box plots are scaled versions which eliminates the bad effects of outliers.
#3e
plot(rawdata$A,rawdata$B,main="Scatterplot of variable A & B",xlab="A",ylab="B")
cor(rawdata[c("A","B")])#The highest numerical value whether positive or negative shows higher correlation
